services:
  - type: web
    runtime: docker
    name: softsolution-portfolio
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildCommand: ""  # Dockerfile maneja todo
    startCommand: ""  # Se usa CMD del Dockerfile (apache2-foreground)
    preDeployCommand: |
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
      php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_KEY
        value: base64:KmNeBEMZDLLmtePmgzw6DkfqpMaMnKQaC2qTPn1fwcQ=
      - key: APP_URL
        value: https://softsolution-portfolio.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql10.freesqldatabase.com
      - key: DB_PORT
        value: '3306'
      - key: DB_DATABASE
        value: sql10802814
      - key: DB_USERNAME
        value: sql10802814
      - key: DB_PASSWORD
        value: tdEWiflKHP
      - key: LOG_CHANNEL
        value: stderr
